"use client";

import Link from "next/link";
import { ArrowRight, Check, Copy, Sparkles } from "lucide-react";
import {
  CYCLE_TARGET, EmptyState, PageHeader, StatTile, StatusBadge, formatDate, getPartnerQrLink, peso, useCopy, usePartner,
} from "./shared";
import MainStoreOverview from "./MainStoreOverview";

export default function OverviewPage() {
  const { dashboard } = usePartner();
  const { copied, copy } = useCopy();

  if (dashboard.partner.store_type === "main") {
    return <MainStoreOverview />;
  }

  const { totals, clicks, points } = dashboard;
  const isAffiliate = dashboard.partner.store_type === "affiliate";
  const conversion = clicks.total > 0 ? (totals.direct_orders / clicks.total) * 100 : 0;
  const shopLink = getPartnerQrLink(dashboard.partner, "shop");
  const recent = dashboard.orders.slice(0, 5);
  const cyclePct = Math.min(100, (points.points_in_cycle / CYCLE_TARGET) * 100);

  return (
    <>
      <PageHeader
        kicker={isAffiliate ? "🌱 Affiliate Partner Dashboard" : "🛍️ Lifestyle Partner Dashboard"}
        title={dashboard.partner.full_name}
        lede="Track orders placed through your shop link and through partners you referred."
      />

      {isAffiliate && (
        <div style={{
          background: "linear-gradient(135deg, #064e3b 0%, #047857 100%)",
          color: "#ffffff",
          borderRadius: "10px",
          padding: "16px 20px",
          marginBottom: "24px",
          display: "flex",
          alignItems: "flex-start",
          gap: "14px",
          boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
        }}>
          <Sparkles aria-hidden="true" size={24} style={{ flexShrink: 0, marginTop: "2px", color: "#fde047" }} />
          <div>
            <strong style={{ fontSize: "15px", display: "block", marginBottom: "4px" }}>
              Welcome to the GutGuard Affiliate Track!
            </strong>
            <p style={{ margin: 0, fontSize: "13px", opacity: 0.95, lineHeight: 1.5 }}>
              Your account starts as an <strong>Affiliate Store</strong>. Share your <strong>Shop QR</strong> to generate your first customer purchase. Once paid, you will automatically upgrade to a <strong>Lifestyle Store</strong> with your personal <strong>Referral QR unlocked</strong>!
            </p>
          </div>
        </div>
      )}

      <section className="pp-stats" aria-label="Summary">
        <StatTile label="Direct orders" value={String(totals.direct_orders)} note={`${clicks.total} shop-link clicks`} />
        <StatTile label="Referred partners" value={String(totals.referred_partners)} note="one referral level" />
        <StatTile label="Referred-partner orders" value={String(totals.referred_orders)} note="generated by partners you referred" />
        <StatTile label="Combined paid value" value={peso(totals.paid_amount)} note="gross order value, not commission" />
      </section>
      <p className="pp-perf">
        Direct conversion: {clicks.total ? `${conversion.toFixed(1)}%` : "--"} · {clicks.last_30_days} clicks in the last 30 days · {totals.paid_orders} paid orders
      </p>

      <div className="pp-grid">
        <section className="pp-card" aria-labelledby="pp-recent">
          <div className="pp-card-head">
            <h2 id="pp-recent">Recent orders</h2>
            <Link href="/partner/orders" className="pp-more">View all <ArrowRight aria-hidden="true" size={14} /></Link>
          </div>
          {recent.length ? (
            <ul className="pp-recent">
              {recent.map((order) => (
                <li key={order.order_code}>
                  <span>
                    <strong>{order.buyer_name || order.buyer_first_name || "A customer"}</strong>
                    <small>{order.order_code} · {formatDate(order.created_at)}</small>
                  </span>
                  <span className="pp-recent-end">
                    <StatusBadge order={order} />
                    <b>{peso(order.total_amount)}</b>
                  </span>
                </li>
              ))}
            </ul>
          ) : (
            <EmptyState title="No attributed orders yet.">Share your shop link or QR code to get started.</EmptyState>
          )}
        </section>

        <div className="pp-stack">
          <section className="pp-card" aria-labelledby="pp-epoints">
            <div className="pp-card-head">
              <h2 id="pp-epoints">E-Points · Cycle {points.current_cycle}</h2>
              <Link href="/partner/e-points" className="pp-more">Details <ArrowRight aria-hidden="true" size={14} /></Link>
            </div>
            <div className="pp-progress-labels">
              <strong>{points.points_in_cycle} pts</strong>
              <span>Target {CYCLE_TARGET}</span>
            </div>
            <div className="pp-progress" role="progressbar" aria-valuemin={0} aria-valuemax={CYCLE_TARGET} aria-valuenow={Math.min(points.points_in_cycle, CYCLE_TARGET)} aria-label="Cycle progress">
              <div style={{ width: `${cyclePct}%` }} />
            </div>
            <p className="pp-muted">
              {points.points_in_cycle < CYCLE_TARGET ? `${CYCLE_TARGET - points.points_in_cycle} points to complete this cycle.` : "Cycle target reached."}
            </p>
          </section>

          <section className="pp-card" aria-labelledby="pp-share">
            <div className="pp-card-head">
              <h2 id="pp-share">Your shop link</h2>
              <Link href="/partner/share" className="pp-more">QR codes <ArrowRight aria-hidden="true" size={14} /></Link>
            </div>
            <p className="partner-link">{shopLink}</p>
            <button type="button" className="shop-primary pp-block-btn" onClick={() => copy(shopLink)}>
              {copied ? <Check aria-hidden="true" size={16} /> : <Copy aria-hidden="true" size={16} />}
              <span>{copied ? "Copied" : "Copy link"}</span>
            </button>
          </section>
        </div>
      </div>
    </>
  );
}
